import 'package:flutter/material.dart';
import 'package:get/get.dart';

class LocalString extends Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'changelang': 'Change Language',
          'internslist': 'Interns List',
          'addnewinterns': 'Add New Interns',
          'addinterndetails': 'Add Intern Details',
          'submit': 'Submit',
          'enteryourname': 'Enter Your Name',
          'name': 'Name',
          'entervalidmobilenumber': 'Enter Valid Mobile Number',
          'mobilenumber': 'Mobile Number',
          'enteryourdesignation': 'Enter Your Designation',
          'designation': 'Designation',
          'entervalidemailid': 'Enter Valid Email ID',
          'email': 'Email',
          'themes': 'Themes',
          'day': 'Day',
          'night': 'Night',
          'choosealanguage':'Choose a language',
          'save':'Save',
        },
        'hi_IN': {
          'changelang': 'भाषा बदलो',
          'internslist': 'इंटर्न सूची',
          'addnewinterns': 'नए इंटर्न जोड़ें',
          'addinterndetails': 'इंटर्न विवरण जोड़ें  ',
          'submit': 'प्रस्तुत करना',
          'enteryourname': 'अपना नाम दर्ज करें',
          'name': 'नाम',
          'entervalidmobilenumber': 'मान्य मोबाइल नंबर दर्ज करें',
          'mobilenumber': 'मोबाइल नंबर',
          'entervalidemailid': 'मान्य ईमेल आईडी दर्ज करें',
          'email': 'ईमेल',
          'enteryourdesignation': 'अपना पदनाम दर्ज करें',
          'designation': 'पद',
          'themes': 'थीम',
          'day': 'दिन',
          'night': 'रात',
          'choosealanguage':'एक भाषा चुनें',
          'save':'बचाना',
        },
        'gu_IN': {
          'changelang': 'ભાષા બદલો',
          'internslist': 'इઈન્ટર્ન યાદી',
          'addnewinterns': 'નવા ઈન્ટર્ન ઉમેરો',
          'addinterndetails': 'ઇન્ટર્ન વિગતો ઉમેરો',
          'submit': 'સબમિટ કરો',
          'enteryourname': 'તમારું નામ દાખલ કરો',
          'name': 'નામ',
          'entervalidmobilenumber': 'માન્ય મોબાઇલ નંબર દાખલ કરો',
          'mobilenumber': 'મોબાઇલ નંબર',
          'entervalidemailid': 'માન્ય ઈમેલ આઈડી દાખલ કરો',
          'email': 'ઈમેલ',
          'enteryourdesignation': 'તમારું હોદ્દો દાખલ કરો',
          'designation': 'હોદ્દો',
          'themes': 'થીમ્સ',
          'day': 'દિવસ',
          'night': 'રાત',
          'choosealanguage':'એક ભાષા પસંદ કરો',
          'save':'સાચવો',
        },
    'mr_IN': {
          'changelang': 'भाषा बदला',
          'internslist': 'इंटर्न यादी',
          'addnewinterns': 'नवीन इंटर्न जोडा',
          'addinterndetails': 'अंतर्गत तपशील जोडा',
          'submit': 'प्रस्तुत करणे',
          'enteryourname': 'आपले नाव प्रविष्ट करा',
          'name': 'नाव',
          'entervalidmobilenumber': 'मला मोबाइल नंबर प्रविष्ट करा',
          'mobilenumber': 'मोबाइल नंबर',
          'entervalidemailid': 'માન ઈમેલ આઈડી દાખલ કરો',
          'email': 'ईमेल',
          'enteryourdesignation': 'तुमचा હોદ્દો दाखल करा',
          'designation': 'होदो',
          'themes': 'सेम्स',
          'day': 'दिवस',
          'night': 'रात्री',
      'choosealanguage':'एक भाषा निवडा',
      'save':'जतन करा',
        },
      };
}
